CC          = c99 
AR          = ar rv
LD          = ld -shared -x

CCOPTIONS   = -O2 -finline-functions -fomit-frame-pointer -funroll-loops 
#CCOPTIONS   = -O2 -finline-functions -fomit-frame-pointer -funroll-loops -m64 -DSTDC_HEADERS 
CDEBUGFLAGS =
