#!/bin/bash -e

cd "$(dirname "$0")"

HELP="Arguments must be:\n\n   Information parameters:
\t-help        : This information

   Commands:
\t-clear       : Clear package
\t-ssm         : Build SSM package
\t-build       : Compile package\n"

CLR=0
BLD=0
SSM=0
REC=0
INS=0

#----- Get arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -clear)   CLR=1;;
        -reconf)  REC=1;;
        -build)   BLD=1;;
        -src)     SRC=1;;
        -ssm)     SSM=1;;
        -install) INS=1;;

        -h|-help)    printf -- "$HELP\n"; exit 0;;
        --)          shift; break;;
        *)           printf -- "Invalid argument $1.\n\n$HELP"; exit 1;;
    esac
    shift
done

#----- Parse MANIFEST file
while IFS= read -r line; do
   if [[ `expr index "$line" ":"` -ne 0 ]]; then
      var=$(echo ${line%%:*} | xargs)
      val=$(echo ${line#*:} | xargs)
      eval $var=\""$val"\"
   fi
done < MANIFEST

#----- SSM packaging stuff
if [[ -n $COMP_ARCH ]]; then
   SSM_COMP=-${COMP_ARCH}
fi
ORDENV_PLAT=${ORDENV_PLAT:-`uname -s`-`uname -m`}
   
SSM_VERSION=${VERSION}${SSM_COMP}
SSM_NAME=${NAME}_${SSM_VERSION}_${ORDENV_PLAT}
mkdir -p ${SSM_DEV}/package/ ${SSM_DEV}/workspace/

MAKE=make

if [[ $CLR -eq 1 ]]; then
   rm -f -r build "${SSM_DEV}/workspace/${SSM_NAME}"
fi

if [[ $SRC -eq 1 || $REC -eq 1 ]]; then
   rm -f -r build
fi

if [[ $BLD -eq 1 ]]; then
   export EC_CMAKE_MODULE_PATH="`pwd`/cmake;$EC_CMAKE_MODULE_PATH"
   export DESTDIR=${SSM_DEV}/workspace/${SSM_NAME}
   export CRAYPE_LINK_TYPE=dynamic

   CMAKE_COMP_FLAGS="-DTCL_SRC_DIR=${SSM_DEV}/src/ext/tcl8.6.6"
   type gdal-config >/dev/null 2>&1 && CMAKE_COMP_FLAGS="$CMAKE_COMP_FLAGS -DGDAL_ROOT=`gdal-config --prefix`" 2>/dev/null

   mkdir -p build
   cd build
   
   #----- Build
   cmake -DCMAKE_INSTALL_PREFIX=$DESTDIR $CMAKE_COMP_FLAGS ../
   $MAKE -j
   $MAKE install 

   cd ..
fi

if [[ $SSM -eq 1 ]]; then

   printf -- "\n----- Building ssm package : ${SSM_DEV}/workspace/${SSM_NAME} -----\n"

   rm -f ${SSM_DEV}/package/${SSM_NAME}.ssm 
   mkdir -p ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d  ${SSM_DEV}/workspace/${SSM_NAME}/etc/profile.d
   ln -fs Dict ${SSM_DEV}/workspace/${SSM_NAME}/bin/o.dict
   cp .ssm.d/post-install ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d

   echo "{
   \"name\": \"${NAME}\",
   \"version\": \"${VERSION}\",
   \"platform\": \"${ORDENV_PLAT}\",
   \"maintainer\": \"${MAINTAINER}\",
   \"summary\": \"${SUMMARY}\",
   \"description\": \"${DESCRIPTION}\",
   \"requires\": \"\",
   \"x-buildinfo\": \"`[ -z "\${ORDENV_SETUP}" ] || git describe --always`\"
}" > ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d/control.json

   cd ${SSM_DEV}/workspace; tar --exclude=.nfs* -zcvf ${SSM_DEV}/package/${SSM_NAME}.ssm ${SSM_NAME}
#   rm -f -r  $(SSM_DEV)/workspace/$(SSM_NAME)
fi

if [[ $INS -eq 1 ]]; then
   $MAKE -f $MAKEFILE install
fi

if [[ $SRC -eq 1 ]]; then
   printf -- "\n----- Building source package : ${SSM_DEV}/src/${NAME}-${VERSION}  -----\n"

   rm -f -r ${SSM_DEV}/src/${NAME}*
   cp -r ../libeerUtils ${SSM_DEV}/src/${NAME}-${VERSION}
   find ${SSM_DEV}/src/${NAME}-${VERSION} -name .git -prune -exec rm -f -r {} \+
fi
