#!/bin/bash
# If changing this file, relfect the changes in libSPI.sh
# post-install <domainHome> <packageHome>

domainHome=$1
packageHome=$2

# create profiles
packageName=`basename ${packageHome}`
profileDirPath=${packageHome}/etc/profile.d
profilePath=${profileDirPath}/${packageName}.sh
loginPath=${profileDirPath}/${packageName}.csh

rm -f ${profilePath} ${loginPath}
mkdir -p ${profileDirPath}

# Added Intel compiler shared lib path ($INTELCOMP_HOME/lib/intel64_lin)
INTELCOMP_HOME=/fs/ssm/main/opt/intelcomp/intelpsxe-cluster-19.0.3.199/intelpsxe-cluster_19.0.3.199_multi
#INTELCOMP_HOME=/fs/ssm/main/opt/intelcomp/intelcomp-2016.1.156/intelcomp_2016.1.156_multi
cat > ${profilePath} << EOF
export EC_INCLUDE_PATH="${packageHome}/include \${EC_INCLUDE_PATH}"
export EC_LD_LIBRARY_PATH="${packageHome}/lib \${EC_LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${packageHome}/lib:${INTELCOMP_HOME}/lib/intel64_lin:\${LD_LIBRARY_PATH}"
EOF

cat > ${loginPath} << EOF
setenv EC_INCLUDE_PATH="${packageHome}/include \${EC_INCLUDE_PATH}" 
setenv EC_LD_LIBRARY_PATH="${packageHome}/lib \${EC_LD_LIBRARY_PATH}" 
setenv LD_LIBRARY_PATH="${packageHome}/lib:${INTELCOMP_HOME}/lib/intel64_lin:\${LD_LIBRARY_PATH}"
EOF
