#!/bin/sh

set -e -x

MAKE=make

#----- Need gmake on AIX
if [[ $HOSTTYPE = "AIX" ]]; then
   MAKE=gmake
fi

#----- Reset __TIMESTAMP__
touch src/App.c

#----- Build no multi processor version first
unset OMPI
$MAKE clear
$MAKE all

#----- Build OpenMP/MPI lib only
export OMPI=-ompi
$MAKE clean
$MAKE lib

while [ "$1" != "" ]; do
    if [ "$1" == "-ssm" ]; then
        $MAKE ssm
    elif [ "$1" == "-install" ]; then
        $MAKE install
    fi
    shift
done

